stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  CI_PROJECT_NAME: "medscribe-ai"
  DOCKER_HARBOR_REGISTRY: "<YOUR_DOCKERHUB_USER>"
  DOCKER_IMAGE: "${DOCKER_HARBOR_REGISTRY}/${CI_PROJECT_NAME}"
  IMAGE_TAG: "latest"

build-job:
  stage: build
  image: docker:latest
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: unix:///var/run/docker.sock
    DOCKER_TLS_CERTDIR: ""
    DOCKER_BUILDKIT: 1  # Enable BuildKit for multi-module Gradle caching
  tags:
    - bdemr
  script:
    - echo "Logging in to Docker Hub..."
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    - echo "Building the Docker image..."
    - docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} .
    - docker push ${DOCKER_IMAGE}:${IMAGE_TAG}

  only:
    - dev

deploy-job:
  stage: deploy
  image: alpine:latest
  tags:
    - bdemr
  before_script:
    - apk add openssh-client
  script:
    - echo "$EC2_SSH_KEY" > key.pem
    - chmod 600 key.pem
    - ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@<YOUR_SERVER_IP> "bash /home/ec2-user/deploy.sh"
  only:
    - dev
