server.port=8086


feature-flagging.base-url=${FEATURE_FLAGGING_SERVICE_URL}

# Reactive PostgreSQL connection
spring.r2dbc.url=r2dbc:postgresql://${PGHOST}/${PGDATABASE}?schema=pfh
spring.r2dbc.username=${PGUSER}
spring.r2dbc.password=${PGPASSWORD}


# URL of your admin server (use the service name if in EKS, or the correct DNS/host)
spring.boot.admin.client.url=${SPRING_ADMIN_SERVER_URL}

spring.boot.admin.client.instance.service-base-url=${MEDSCRIBEAI_SERVICE_URL}

# If you enabled security on the admin server, set credentials:
spring.boot.admin.client.username=${ADMIN_SERVER_USERNAME}
spring.boot.admin.client.password=${ADMIN_SERVER_PASS}
