server.port=8086

feature-flagging.base-url=http://localhost:8087

# PostgreSQL
#spring.r2dbc.url=r2dbc:postgresql://${PGHOST:localhost}:5432/pfh?schema=pfh
spring.r2dbc.url=r2dbc:postgresql://${PGHOST:localhost}:5432/medscribe?schema=medscribe
spring.r2dbc.username=${PGUSER:postgres}
spring.r2dbc.password=${PGPASSWORD:changeme}
